### ISSUE TITLE
全体的にページのviewを統一

### ISSUE THREAD

**Issue by stsnkmr** [Hackthon-2020/SANPAI#5]
navbarをどうするか。
背景の追加
ロゴマークの配置等

**Comment by stsnkmr** [comment]
#4 navbar改良&favicon実装&最初のページをテキトーに置いてみました。

**Comment by Soshi-1114** [comment]
@stsnkmr 
#番号間違えてないかな？
header footer　はどうしようか

**Comment by stsnkmr** [comment]
@ 修正した。
header footer 共に載せる物がないからシンプルかつ簡単に用意しました。
この状態で作業誰かにパスしたいです。
24日は稼働できないので。
![image](https://user-images.githubusercontent.com/32321073/103011099-b6332b00-457c-11eb-969e-b5559fc44b93.png)

**Comment by Soshi-1114** [comment]
プルリクしないとまーじできないっす
@stsnkmr
